title:             Portfolio Robin Jaspers
email:             f/mayzowpj
subtitle:          Portfolio
author:            Robin Jaspers
#url:               "localhost:4000"
url:               "http://AyuCalices.github.io/"
baseurl:           ""

# Social Profiles
linkedin_username: robin-jaspers-862656256
github_username:   AyuCalices
email_address:     r.jaspers18@gmail.com

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
