title:             Portfolio Robin Jaspers
email:             r.jaspers18@gmail.com
subtitle:          Portfolio
author:            Robin Jaspers
#url:               "localhost:4000"
url:               "http://AyuCalices.github.io/"
baseurl:           ""

# Social Profiles
#twitter_username:  SBootstrap
github_username:   AyuCalices
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
